-- Step 3a: Flatten Tech Terms into Fact Table
CREATE OR REPLACE TABLE FCT_TECH_TERMS AS
SELECT
    VIDEO_ID,
    f.value::STRING AS TECH_TERM,
    INSERTED_AT AS PROCESSED_AT
FROM STG_YOUTUBE_TRANSCRIPTS,
LATERAL FLATTEN(input => TECH_TERMS_ARRAY) f;

-- Step 3b: Flatten Book Mentions into Fact Table
CREATE OR REPLACE TABLE FCT_BOOK_MENTIONS AS
SELECT
    VIDEO_ID,
    f.value::STRING AS BOOK_NAME,
    INSERTED_AT AS PROCESSED_AT
FROM STG_YOUTUBE_TRANSCRIPTS,
LATERAL FLATTEN(input => BOOK_NAMES_ARRAY) f;
